import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import { execSync } from "child_process";

function buildId() {
  try {
    const hash = execSync("git rev-parse --short HEAD").toString().trim();
    let dirty = "";
    try {
      if (execSync("git status --porcelain").toString().trim()) dirty = "-dirty";
    } catch {}
    return hash + dirty;
  } catch {
    return "unknown";
  }
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: { __BUILD_ID__: JSON.stringify(buildId()) },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
