#!/usr/bin/env python3
"""Generate src/oneDriveIcons.ts from the raw OneDrive file-type SVGs in src/icons/onedrive/.

Each source SVG references its gradients by single-letter ids (a, b, c…) that are IDENTICAL across
all 18 icons. Inlining several into one DOM (Obsidian renders our SVGs via innerHTML) would let
`url(#a)` resolve to the FIRST `#a` on the page → wrong colors. So this namespaces every id per icon
(e.g. docx-a) so they're collision-safe, then emits a TS module:

  ONEDRIVE_ICONS        name -> namespaced inline SVG string
  ONEDRIVE_EXT_TO_ICON  lowercase extension (no dot) -> icon name
  oneDriveIconForName() filename -> SVG string | null

PRE-PUBLISH (docs/roadmap.md): these are Microsoft's OneDrive product icons (their IP). Replace with
original artwork before shipping to the community store. Personal use only until then.

Run:  python3 scripts/gen-onedrive-icons.py
"""
import json, os, re, glob

HERE = os.path.dirname(os.path.abspath(__file__))
ICON_DIR = os.path.join(HERE, "..", "src", "icons", "onedrive")
OUT = os.path.join(HERE, "..", "src", "oneDriveIcons.ts")

# Extension -> icon. The CORE is AUTHORITATIVE — extracted from OneDrive's actual rendering in the
# saved page (each dummy file's <img src=".../<icon>.svg" alt=".<ext>">), 107 extensions across 29
# icons, so it is exactly what OneDrive assigns. Non-obvious calls worth knowing: ts -> video (it's
# MPEG transport stream, not TypeScript!); ogg -> video; webp/rs/msix/msu/3dm/hwp/com -> genericfile;
# ppt/pptx -> pptx but key/odp -> presentation; xls/xlsx -> xlsx but numbers/ods/tsv -> spreadsheet;
# odt/pages/epub -> rtf; psd -> photo; dwg -> model; bat/cmd/ini/log/md -> code.
# SIBLINGS = a few ultra-obvious, common extensions absent from the sample, same family as an
# authoritative member. AUTHORITATIVE wins on any conflict.
AUTHORITATIVE = {
    "accdb": ["accdb", "mdb"],
    "archive": ["7z", "gz", "iso", "rar", "tar"],
    "audio": ["aac", "flac", "m4a", "mid", "mp3", "wav", "wma"],
    "code": ["bat", "c", "cmd", "cpp", "cs", "css", "go", "ini", "java", "js", "json", "log", "md",
             "php", "py", "rb", "sh", "sql", "yaml", "yml"],
    "csv": ["csv"],
    "docx": ["doc", "docx"],
    "email": ["eml", "msg"],
    "exe": ["app", "appx", "exe", "msi"],
    "font": ["otf", "ttf"],
    "genericfile": ["3dm", "com", "hwp", "hwpx", "msix", "msu", "rs", "webp"],
    "html": ["htm", "html", "mht", "mhtml"],
    "model": ["dwg"],
    "mpp": ["mpp"],
    "one": ["one"],
    "pdf": ["pdf"],
    "photo": ["bmp", "gif", "heic", "ico", "jpg", "png", "psd", "tif", "tiff"],
    "pptx": ["ppt", "pptx"],
    "presentation": ["key", "odp"],
    "pub": ["pub"],
    "rtf": ["epub", "odt", "pages", "rtf"],
    "spreadsheet": ["numbers", "ods", "tsv"],
    "sysfile": ["bak", "dat", "dll"],
    "txt": ["txt"],
    "vector": ["ai", "eps", "svg", "xps"],
    "video": ["avi", "flv", "m4v", "mkv", "mov", "mp4", "mpg", "ogg", "ts", "webm", "wmv"],
    "vsdx": ["vsd", "vsdx"],
    "xlsx": ["xls", "xlsx"],
    "xml": ["xml"],
    "zip": ["zip"],
}
SIBLINGS = {
    "photo": ["jpeg", "heif"],
    "code": ["tsx", "jsx", "mjs", "cjs", "scss", "less", "bash", "zsh", "vue", "svelte"],
}
EXT_TO_ICON = {}
for _icon, _exts in SIBLINGS.items():
    for _e in _exts:
        EXT_TO_ICON[_e] = _icon
for _icon, _exts in AUTHORITATIVE.items():  # authoritative overrides any sibling guess
    for _e in _exts:
        EXT_TO_ICON[_e] = _icon


def namespace(svg, prefix):
    """Prefix every `id="x"` (and its `url(#x)` references) with `<prefix>-` so icons don't collide."""
    ids = sorted(set(re.findall(r'id="([^"]+)"', svg)), key=len, reverse=True)
    for v in ids:
        svg = svg.replace(f'id="{v}"', f'id="{prefix}-{v}"')
        svg = svg.replace(f"url(#{v})", f"url(#{prefix}-{v})")
    return svg


icons = {}
for path in sorted(glob.glob(os.path.join(ICON_DIR, "*.svg"))):
    name = os.path.splitext(os.path.basename(path))[0]
    icons[name] = namespace(open(path, encoding="utf-8").read().strip(), name)

# sanity: every mapped icon name must exist as a source SVG
missing = sorted({v for v in EXT_TO_ICON.values() if v not in icons})
if missing:
    raise SystemExit(f"EXT_TO_ICON references missing icons: {missing}")

icon_body = ",\n".join(f"  {json.dumps(n)}: {json.dumps(svg)}" for n, svg in sorted(icons.items()))
ext_body = ",\n".join(f"  {json.dumps(e)}: {json.dumps(EXT_TO_ICON[e])}" for e in sorted(EXT_TO_ICON))

ts = f"""// AUTO-GENERATED by scripts/gen-onedrive-icons.py — do not edit by hand.
// Source SVGs: src/icons/onedrive/*.svg (Microsoft OneDrive file-type icons, Fluent style, 32×32).
// Every icon's gradient ids are namespaced (e.g. docx-a) so multiple inline SVGs are collision-safe.
// PRE-PUBLISH (docs/roadmap.md): Microsoft's product icons (IP) — replace with original artwork
// before publishing to the community store. Personal use only until then.

// Icon name -> inline SVG markup (sized via CSS; viewBox 0 0 32 32, no width/height).
export const ONEDRIVE_ICONS: Record<string, string> = {{
{icon_body}
}};

// Lowercase file extension (no dot) -> icon name. (No pdf/xlsx here — fall back to your own icons.)
export const ONEDRIVE_EXT_TO_ICON: Record<string, string> = {{
{ext_body}
}};

// The OneDrive SVG for a filename's extension, or null when there's no mapping.
export function oneDriveIconForName(name: string): string | null {{
  const dot = name.lastIndexOf(".");
  const ext = dot >= 0 ? name.slice(dot + 1).toLowerCase() : "";
  const icon = ONEDRIVE_EXT_TO_ICON[ext];
  return icon ? ONEDRIVE_ICONS[icon] ?? null : null;
}}
"""

open(OUT, "w", encoding="utf-8").write(ts)
print(f"wrote {os.path.relpath(OUT)}: {len(icons)} icons, {len(EXT_TO_ICON)} extension mappings, {os.path.getsize(OUT)//1024} KB")
