export interface PanelDragModifierState {
  metaKey: boolean;
  ctrlKey: boolean;
  altKey: boolean;
  shiftKey: boolean;
}

type ModifierEvent = Pick<DragEvent | KeyboardEvent, keyof PanelDragModifierState>;

const NO_MODIFIERS: PanelDragModifierState = {
  metaKey: false,
  ctrlKey: false,
  altKey: false,
  shiftKey: false,
};

/** Tracks the modifiers currently held during one panel row drag. */
export class PanelDragModifierTracker {
  private active = false;
  private state: PanelDragModifierState = { ...NO_MODIFIERS };

  private readonly handleKeyStateChange = (evt: KeyboardEvent): void => {
    if (this.active) {
      this.state = readModifierState(evt);
    }
  };

  start(evt: DragEvent): void {
    this.stop();
    this.active = true;
    this.state = readModifierState(evt);
    document.addEventListener("keydown", this.handleKeyStateChange, true);
    document.addEventListener("keyup", this.handleKeyStateChange, true);
  }

  stop(): void {
    document.removeEventListener("keydown", this.handleKeyStateChange, true);
    document.removeEventListener("keyup", this.handleKeyStateChange, true);
    this.active = false;
    this.state = { ...NO_MODIFIERS };
  }

  // The passed event's OWN modifier flags are the freshest signal for "what's held NOW" — a `dragover`
  // or `editor-drop` is generated by the OS with the live modifierFlags at that instant. The
  // keydown/keyup tracker only ADDS a modifier the event missed (one pressed while the pointer was
  // stationary, IF the platform delivered keydown during the drag). So OR the two rather than letting
  // the tracker SHADOW the event: on macOS a native (Cocoa) drag runs a nested event loop that may not
  // deliver keydown/keyup to the document, which would freeze the tracker at its dragstart snapshot and
  // silently drop a held ⌥/⇧ (and never trigger the ⌘→"move" dragover). OR-ing recovers the proven
  // read-from-event behavior while keeping the tracker's upside. Trade-off: a modifier RELEASED before
  // drop whose keyup the OS dropped could latch — but the documented use holds the modifier THROUGH the
  // drop, so the event reports it and the tracker agrees. When inactive (foreign/synthetic payload whose
  // dragstart we never saw), fall back to the event alone.
  current(evt?: ModifierEvent): PanelDragModifierState {
    const event = evt ? readModifierState(evt) : { ...NO_MODIFIERS };
    if (!this.active) {
      return event;
    }
    return {
      metaKey: this.state.metaKey || event.metaKey,
      ctrlKey: this.state.ctrlKey || event.ctrlKey,
      altKey: this.state.altKey || event.altKey,
      shiftKey: this.state.shiftKey || event.shiftKey,
    };
  }
}

function readModifierState(evt: ModifierEvent): PanelDragModifierState {
  return {
    metaKey: evt.metaKey,
    ctrlKey: evt.ctrlKey,
    altKey: evt.altKey,
    shiftKey: evt.shiftKey,
  };
}
